# ⚙️ Arquivo de Configuração - config.yaml

# Este arquivo pode ser usado para personalizar o comportamento da conversão
# Copie e modifique conforme necessário

# =============================================================================
# CONFIGURAÇÕES BÁSICAS
# =============================================================================

input:
  # Arquivo PDF a ser convertido
  pdf_file: "Revenue_Architecture.pdf"
  
  # Caminho completo (deixe vazio para usar /mnt/user-data/uploads/)
  pdf_path: ""

output:
  # Nome da skill gerada (auto-detectado do PDF se vazio)
  skill_name: ""
  
  # Diretório de output (padrão: /mnt/user-data/outputs/)
  output_dir: "/mnt/user-data/outputs"
  
  # Mover automaticamente para /mnt/skills/user/ após criação?
  auto_install: false

# =============================================================================
# MODO DE CONVERSÃO
# =============================================================================

conversion:
  # Modo: "basico" ou "premium"
  mode: "basico"
  
  # Usar refinamento com LLM (apenas se mode = "premium")
  llm_refinement: true
  
  # Nível de otimização: "basic", "standard", "maximum"
  optimization_level: "maximum"
  
  # Usar API Anthropic para refinamento (requer API key)
  use_anthropic_api: false
  anthropic_api_key: ""  # Ou use variável de ambiente ANTHROPIC_API_KEY

# =============================================================================
# CONTEXTUALIZAÇÃO (Modo Premium)
# =============================================================================

context:
  # Contexto do negócio (para adaptar exemplos)
  business: "B2B SaaS"
  
  # Principais casos de uso
  use_cases:
    - "Revenue operations"
    - "Sales enablement"
    - "Marketing strategy"
  
  # Para quem adaptar os exemplos
  adapt_for:
    - "Sua empresa"
    - "Seu setor"
    - "Seu mercado"
  
  # Indústria/setor
  industry: "SaaS"
  
  # Público-alvo
  target_audience:
    - "Founders"
    - "Operations professionals"
    - "Business leaders"

# =============================================================================
# PROCESSAMENTO DE CONTEÚDO
# =============================================================================

processing:
  # Detectar e extrair tabelas
  extract_tables: true
  
  # Detectar e extrair blocos de código
  extract_code_blocks: true
  
  # Detectar e extrair listas
  extract_lists: true
  
  # Identificar e extrair frameworks/metodologias
  extract_frameworks: true
  
  # Comprimento mínimo de seção (em caracteres)
  min_section_length: 100
  
  # Tokens máximos por capítulo (divide se exceder)
  max_tokens_per_chapter: 15000

# =============================================================================
# GERAÇÃO DE CONTEÚDO
# =============================================================================

content_generation:
  # Gerar TL;DR para cada capítulo
  generate_tldr: true
  
  # Comprimento máximo do TL;DR (em caracteres)
  tldr_max_length: 200
  
  # Gerar FAQs para cada capítulo
  generate_faqs: true
  
  # Número de FAQs por capítulo
  faqs_per_chapter: 5
  
  # Gerar resumo executivo do livro completo
  generate_executive_summary: true
  
  # Gerar glossário de termos
  generate_glossary: true
  
  # Número mínimo de ocorrências para incluir no glossário
  glossary_min_frequency: 3

# =============================================================================
# OTIMIZAÇÕES
# =============================================================================

optimization:
  # Criar estrutura em camadas (TL;DR → Resumo → Completo)
  layered_content: true
  
  # Gerar índice semântico
  semantic_index: true
  
  # Gerar mapa de conhecimento (dependências entre capítulos)
  knowledge_map: true
  
  # Gerar matriz de aplicabilidade
  applicability_matrix: true
  
  # Contextos para matriz de aplicabilidade
  applicability_contexts:
    - "B2B"
    - "B2C"
    - "SaaS"
    - "Product"
    - "Startup"
    - "Enterprise"

# =============================================================================
# ARTEFATOS
# =============================================================================

artifacts:
  # Gerar apresentação executiva
  generate_presentation: true
  
  # Número de slides na apresentação
  presentation_slides: 15
  
  # Gerar plano de implementação
  generate_implementation_plan: true
  
  # Duração do plano (em dias)
  implementation_plan_days: 90
  
  # Gerar one-pager
  generate_one_pager: true

# =============================================================================
# ANÁLISE SEMÂNTICA
# =============================================================================

semantic_analysis:
  # Identificar conceitos-chave
  identify_concepts: true
  
  # Método: "frequency" (básico) ou "llm" (premium)
  concept_identification_method: "frequency"
  
  # Mapear dependências entre capítulos
  map_dependencies: true
  
  # Detectar contradições/nuances
  detect_contradictions: true
  
  # Construir índice de relações entre conceitos
  build_concept_relations: true
  
  # Número máximo de conceitos relacionados por conceito
  max_related_concepts: 10

# =============================================================================
# METADADOS
# =============================================================================

metadata:
  # Gerar metadata.json completo
  generate_metadata: true
  
  # Incluir estatísticas detalhadas
  include_statistics: true
  
  # Gerar changelog
  generate_changelog: true
  
  # Versão inicial da skill
  initial_version: "1.0.0"

# =============================================================================
# VALIDAÇÃO
# =============================================================================

validation:
  # Validar output após geração
  validate_output: true
  
  # Checagens a realizar
  checks:
    - "skill_md_exists"
    - "chapters_generated"
    - "metadata_valid"
    - "structure_complete"
    - "links_functional"
  
  # Ação se validação falhar: "warn" ou "abort"
  on_validation_failure: "warn"

# =============================================================================
# PERFORMANCE
# =============================================================================

performance:
  # Processar capítulos em paralelo (se possível)
  parallel_processing: false
  
  # Número de workers para processamento paralelo
  num_workers: 4
  
  # Cache de processamentos intermediários
  use_cache: true
  
  # Diretório de cache
  cache_dir: "/tmp/pdf-to-skill-cache"

# =============================================================================
# LOGGING
# =============================================================================

logging:
  # Nível de log: "DEBUG", "INFO", "WARNING", "ERROR"
  level: "INFO"
  
  # Mostrar progresso detalhado
  verbose: true
  
  # Mostrar uso de tokens em tempo real
  show_token_usage: true
  
  # Salvar log em arquivo
  save_to_file: false
  
  # Arquivo de log
  log_file: "conversion.log"

# =============================================================================
# AVANÇADO
# =============================================================================

advanced:
  # Customizar prompts para LLM (se mode = "premium")
  custom_prompts:
    tldr: ""  # Deixe vazio para usar padrão
    faq: ""
    contextualization: ""
  
  # Regras customizadas de detecção de estrutura
  custom_chapter_patterns:
    # Adicione padrões regex customizados
    # - "^SECÇÃO\s+\d+"
  
  # Stopwords customizadas (adiciona às padrão)
  custom_stopwords:
    # - "palavra1"
    # - "palavra2"
  
  # Pós-processamento customizado
  custom_post_processing: false
  custom_post_processing_script: ""

# =============================================================================
# NOTAS
# =============================================================================

# Como usar este arquivo:
# 
# 1. Copie este arquivo para config.yaml
# 2. Modifique os valores conforme necessário
# 3. Referencie na conversão (se suportado)
#
# Ou simplesmente use como referência para entender
# todas as opções disponíveis na conversão.
#
# Para modo interativo padrão, Claude perguntará
# as configurações essenciais (modo, contexto, etc.)
# e usará defaults sensatos para o resto.
